from . import account_invoice
from . import account_invoice_line
from . import account_payment
from . import crm_lead
from . import oniad_accountmanager
from . import oniad_address
from . import oniad_campaign
from . import oniad_country
from . import oniad_country_state
from . import oniad_transaction
from . import oniad_user
from . import oniad_user_tag
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import survey_user_input