# -*- coding: utf-8 -*-
from . import res_partner
from . import res_partner_partner_type
from . import res_partner_stakeholder_type
from . import res_partner_fan_level
from . import res_partner_inversor_type
from . import res_partner_educational_center_type
from . import res_partner_formation_type
from . import res_partner_asociation_type
from . import res_partner_asociation_geo
from . import res_partner_communicator_type
from . import res_partner_social_network
from . import res_partner_communication_area
from . import res_partner_communication_geo
from . import res_partner_user_type
from . import res_partner_customer_type
from . import res_partner_agency_type
from . import res_partner_market_target
from . import res_partner_sector
from . import res_partner_activity
from . import res_partner_agency_activity