# -*- coding: utf-8 -*-
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
import res_partner
import res_partner_partner_type
import res_partner_stakeholder_type
import res_partner_fan_level
import res_partner_inversor_type
import res_partner_educational_center_type
import res_partner_formation_type
import res_partner_asociation_type
import res_partner_asociation_geo
import res_partner_communicator_type#falta
import res_partner_social_network
import res_partner_communication_area
import res_partner_communication_geo
import res_partner_user_type
import res_partner_customer_type
import res_partner_agency_type
import res_partner_market_target
import res_partner_sector
import res_partner_activity
import res_partner_agency_activity